package Vista;

/**
 *
 * @author omar
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public FrmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbImagen = new javax.swing.JLabel();
        jMenuBarInicio = new javax.swing.JMenuBar();
        menuEmpleados = new javax.swing.JMenu();
        menuItemAsalariado = new javax.swing.JMenuItem();
        menuItemPorHoras = new javax.swing.JMenuItem();
        menuItemPorComision = new javax.swing.JMenuItem();
        menuItemBaseMasComision = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuNomina = new javax.swing.JMenu();
        menuItemGeneraNomina = new javax.swing.JMenuItem();
        menuFactura = new javax.swing.JMenu();
        menuItemGenerarFactura = new javax.swing.JMenuItem();
        menuItemVisualizarFacturas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 51, 255));
        lbTitulo.setText("Sistema de Recursos Humanos");

        lbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/rh.jpeg"))); // NOI18N

        menuEmpleados.setText("Empleados");

        menuItemAsalariado.setText("Asalariado");
        menuItemAsalariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAsalariadoActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemAsalariado);

        menuItemPorHoras.setText("Por Horas");
        menuItemPorHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPorHorasActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemPorHoras);

        menuItemPorComision.setText("Por Comision");
        menuItemPorComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPorComisionActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemPorComision);

        menuItemBaseMasComision.setText("Base más Comisión");
        menuItemBaseMasComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBaseMasComisionActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemBaseMasComision);

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemSalir);

        jMenuBarInicio.add(menuEmpleados);

        menuNomina.setText("Nómina");

        menuItemGeneraNomina.setText("Genera nómina");
        menuItemGeneraNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGeneraNominaActionPerformed(evt);
            }
        });
        menuNomina.add(menuItemGeneraNomina);

        jMenuBarInicio.add(menuNomina);

        menuFactura.setText("Factura");

        menuItemGenerarFactura.setText("Generar Factura");
        menuItemGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGenerarFacturaActionPerformed(evt);
            }
        });
        menuFactura.add(menuItemGenerarFactura);

        menuItemVisualizarFacturas.setText("Visualizar Facturas");
        menuItemVisualizarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarFacturasActionPerformed(evt);
            }
        });
        menuFactura.add(menuItemVisualizarFacturas);

        jMenuBarInicio.add(menuFactura);

        setJMenuBar(jMenuBarInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbImagen)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(lbImagen)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAsalariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAsalariadoActionPerformed
        // TODO add your handling code here:
        new FrmEmpleadoAsalariado().setVisible(true);

    }//GEN-LAST:event_menuItemAsalariadoActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemPorHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPorHorasActionPerformed
        // TODO add your handling code here:
        new FrmEmpleadoPorHoras().setVisible(true);

    }//GEN-LAST:event_menuItemPorHorasActionPerformed

    private void menuItemPorComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPorComisionActionPerformed
        // TODO add your handling code here:
        new FrmEmpleadoPorComision().setVisible(true);

    }//GEN-LAST:event_menuItemPorComisionActionPerformed

    private void menuItemBaseMasComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBaseMasComisionActionPerformed
        // TODO add your handling code here:
        new FrmEmpleadoBaseMasComision().setVisible(true);
    }//GEN-LAST:event_menuItemBaseMasComisionActionPerformed

    private void menuItemGeneraNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGeneraNominaActionPerformed
        // TODO add your handling code here:
        new FrmNomina().setVisible(true);
    }//GEN-LAST:event_menuItemGeneraNominaActionPerformed

    private void menuItemGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGenerarFacturaActionPerformed
        // TODO add your handling code here:
        new FrmGenerarFactura().setVisible(true);
    }//GEN-LAST:event_menuItemGenerarFacturaActionPerformed

    private void menuItemVisualizarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarFacturasActionPerformed
        // TODO add your handling code here:
        new FrmFacturas().setVisible(true);
    }//GEN-LAST:event_menuItemVisualizarFacturasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarInicio;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenu menuFactura;
    private javax.swing.JMenuItem menuItemAsalariado;
    private javax.swing.JMenuItem menuItemBaseMasComision;
    private javax.swing.JMenuItem menuItemGeneraNomina;
    private javax.swing.JMenuItem menuItemGenerarFactura;
    private javax.swing.JMenuItem menuItemPorComision;
    private javax.swing.JMenuItem menuItemPorHoras;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemVisualizarFacturas;
    private javax.swing.JMenu menuNomina;
    // End of variables declaration//GEN-END:variables
}
